### ISSUE TITLE
download bytes question

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [crifurch/pure_ftp#19]
thank you for fixing the download error, 

now when downloading using 
<img width="658" alt="image" src="https://github.com/crifurch/pure_ftp/assets/25157308/0b74143a-d42a-4bd9-aa0f-e2f928d8d8bb">

the perenctage is always 100 % 
<img width="506" alt="image" src="https://github.com/crifurch/pure_ftp/assets/25157308/e09a74e7-0586-4a66-a6f0-5ef361231baf">

i think the problem is the total bytes is not the actual total bytes

should i get the real total bytes from the `file.info.size`?

**Comment by crifurch** [comment]
yes, because in another issue in logs i'm found this
```
flutter: [2024-05-16 11:42:53.238135] 192.168.1.5:15114> SIZE /Download/Anime_here/One Piece/One Piece ep 968 1920x1080.ts.mkv
flutter: [2024-05-16 11:42:53.541526] 192.168.1.5:15114< 550 No directory traversal allowed in SIZE param
```

**Comment by abdelaziz-mahdy** [comment]
Okay thank you for your awesome work❤️
