### ISSUE TITLE
Conflict Between pure_ftp and Flutter SDK Versions

### ISSUE THREAD

**Issue by samfilholima** [crifurch/pure_ftp#20]
Hi there, I'm encountering an issue with the pure_ftp library. The error message states:

Because pure_ftp >=0.6.0 depends on meta ^1.15.0 and every version of flutter from sdk depends on meta 1.12.0, pure_ftp >=0.6.0 is incompatible with flutter from sdk. So, because sb_promotor depends on both flutter from sdk and pure_ftp ^0.7.1, version solving failed.

I'm currently using Flutter version 3.22.0. Could you please advise on how I can resolve this? Thank you.

**Comment by crifurch** [comment]
dev_overrides:
   meta: ^1.12.0

**Comment by crifurch** [comment]
@samfilholima this should resolve your problrem

**Comment by abdelaziz-mahdy** [comment]
```
dependency_overrides:
  meta: ^1.12.0
```

**Comment by samfilholima** [comment]
thanks. It worked
