### ISSUE TITLE
Ftp server

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [crifurch/pure_ftp#22]
I wanted to know if you have the knowledge to make a ftp server using dart, I would love to transfer files from mobile to other mobile 

Or mobile to desktop using ftp, 

So a dart ftp server will help alot.

If you have the sources I can follow to make a package let me know, I would love to create it

**Comment by crifurch** [comment]
It was in my plans to create package for ftp server, but now i haven't enough time to create it

**Comment by abdelaziz-mahdy** [comment]
If you can provide the sources for the understanding of it, let me know I can implement it and add you as a collaborator,

Since I like the way you wrote this package

**Comment by crifurch** [comment]
Unfortunately, i haven't any source of ftp server, may be on weekends I'll investigate. Now i have mind only about network layer

**Comment by abdelaziz-mahdy** [comment]
I will try to do it, if I was able to implement any of it's features will let you know

**Comment by abdelaziz-mahdy** [comment]
i was able to create this https://pub.dev/packages/ftp_server, feel free to checkout and help if you found a problem with it, i tested it using your awesome client package which i created a client with here https://github.com/abdelaziz-mahdy/ftp_client 

right now i tested the package on macos, i think the only problem will be windows due to the different path style

**Comment by crifurch** [comment]
Great, but a lot of things  need to be changed

**Comment by abdelaziz-mahdy** [comment]
> Great, but a lot of things  need to be changed

Feel free to open a pr/ or an issue and let's discuss what can be done

**Comment by crifurch** [comment]
I have completely another vision of code, you can find WIP implementation here https://github.com/crifurch/pure_ftp_server

**Comment by abdelaziz-mahdy** [comment]
Well I think the only difference I see is how you handle the commands and how to write them the rest is 90% the same 

Anyway I think you want to create your own package not contribute to mine, so I wish you the best of luck and if you need any help let me know I would love to help whenever I can

**Comment by crifurch** [comment]
In your implementation very low abstraction level, that prevent to have some features e.g. in memory storage, one file storage, get statistic that i want to have in future. btw thanks for create my vision on that

**Comment by abdelaziz-mahdy** [comment]
i am willing to try to make every abstract able and changeable, so i will have another try in a new branch, when i finish it will share it with you, and lets discuss what is better and go with it

**Comment by abdelaziz-mahdy** [comment]
https://github.com/abdelaziz-mahdy/ftp_server/tree/abstract is my work on the abstraction.

**Comment by crifurch** [comment]
little bit not that i mentioned

**Comment by abdelaziz-mahdy** [comment]
Well I guess I am lost on what you want to achieve 😅

**Comment by crifurch** [comment]
Check my last updates in server repo, i don't know better way to share my vision

**Comment by abdelaziz-mahdy** [comment]
Okay, got it you want to abstract the underlaying file systems, well will try that too

for now you can check the repo i was able to add memory file operations, but i am not using entries the same way you do, so let me know what you think and we can migrate it to a better way if you like


also is there a better way to communicate instead of github? just to have better understanding of each other thoughts?

**Comment by crifurch** [comment]
Do you use Telegram or WhatsApp?

**Comment by abdelaziz-mahdy** [comment]
> Do you use Telegram or WhatsApp?
> 

Yes I use WhatsApp, but i don't want to share my number on GitHub, 

Discord works for me too if you have it

**Comment by crifurch** [comment]
Yes, id same as my developer name in git
