### ISSUE TITLE
File Download Issue: Bytes Received Smaller Than Expected

### ISSUE THREAD

**Issue by samfilholima** [crifurch/pure_ftp#23]
Hi there,

I’ve been using your library to download files, and I noticed an issue. When downloading a file of approximately 3.38 MB, the received bytes appear to be smaller than expected. However, it’s worth noting that files with a size of less than 600 KB seem to function normally. Could you please investigate this issue and provide any insights or solutions?

Thanks in advance for your help!

**Comment by crifurch** [comment]
Hi, try client.socket.setTransferType(FtpTransferType.binary);

**Comment by crifurch** [comment]
@samfilholima or you can pass it by default as in https://github.com/crifurch/pure_ftp/issues/24#issuecomment-2118479618

**Comment by samfilholima** [comment]
hi friend, thank you! It worked out perfectly
