### ISSUE TITLE
download never completes?

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [crifurch/pure_ftp#24]
i think the download function is waiting for a command

```

flutter: [2024-05-17 17:03:35.753097] 192.168.1.5:60859> SIZE /Anya/Desktop/Screenshot 2022-05-21 190952.png
flutter: [2024-05-17 17:03:36.057139] 192.168.1.5:60859< 550 No directory traversal allowed in SIZE param
flutter: [2024-05-17 17:03:36.058355] 192.168.1.5:60859> PASV
flutter: [2024-05-17 17:03:36.361158] 192.168.1.5:60859< 227 Entering Passive Mode (192,168,1,5,181,75).
flutter: [2024-05-17 17:03:36.397860] 192.168.1.5:60859> RETR /Anya/Desktop/Screenshot 2022-05-21 190952.png
flutter: [2024-05-17 17:03:36.700702] 192.168.1.5:60859< 150 Sending file
226 Transmission finished
flutter: downloaded: 215402 of 215402, 100.0% calculated 100.0%, speed: Infinity MB/second
flutter: Downloaded 215402 of 215402 bytes
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FtpException: Timeout reached for Receiving response!
#0      FtpSocket.read.<anonymous closure> (package:pure_ftp/src/ftp/ftp_socket.dart:163:7)
#1      _RootZone.run (dart:async/zone.dart:1655:54)
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:943:34)
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

but if that command is `226 Transmission finished` it got sent, but looks like it got sent before the file could finish copying 

anyway to know what is the problem?

**Comment by abdelaziz-mahdy** [comment]
tested using another ftp server, that the message gets sent after finishing the copying 
<img width="868" alt="image" src="https://github.com/crifurch/pure_ftp/assets/25157308/ffb939a4-82df-4196-a757-c02139b4e271">

it works correctly there.

**Comment by crifurch** [comment]
oh, i'm found problem

**Comment by crifurch** [comment]
i will try fix it in few moments

**Comment by crifurch** [comment]
@abdelaziz-mahdy  try this https://github.com/crifurch/pure_ftp/tree/fix/dowload_wait_response_error, i tested on large file? i think it is not necessary to wait some response after download

**Comment by crifurch** [comment]
now it should works as expected

**Comment by abdelaziz-mahdy** [comment]
the flush is needed, i will test again, since the files gets downloaded but corrupted

**Comment by crifurch** [comment]
pls try test in now, remove pubspec.lock before pub get

**Comment by abdelaziz-mahdy** [comment]
btw flutter upgrade should get the updated without the need to delete the lock, but will try it

**Comment by crifurch** [comment]
and don't forget change to binary transfer if you are download some not text filles

**Comment by abdelaziz-mahdy** [comment]
changing to binary fixed the corrupted problem, should that be the default? most of the ftp downloads are not text files if i am correct
`client.socket.setTransferType(FtpTransferType.binary);`

**Comment by crifurch** [comment]
in auto mode i had 
```
Downloaded 24467980 of 24468684 bytes
Downloaded 24469428 of 24469428 bytes
```
if i used 
`
  await client.socket.setTransferType(FtpTransferType.binary);`

i had only
```
Downloaded 24468304 of 24468684 bytes
Downloaded 24468684 of 24468684 bytes
Disconnecting from 192.168.1.200:21
```

**Comment by crifurch** [comment]
> changing to binary fixed the corrupted problem, should that be the default? most of the ftp downloads are not text files if i am correct `client.socket.setTransferType(FtpTransferType.binary);`

i think yes but in many cases ftp clients use auto mode as default

**Comment by crifurch** [comment]
you can use
```
FtpClient(
    socketInitOptions: FtpSocketInitOptions(
      host: config['host'],
      port: config['port'],
      transferType: FtpTransferType.binary,
    ),
    authOptions: FtpAuthOptions(
      username: config['username'],
      password: config['password'],
      account: config['account'],
    ),
    logCallback: print,
  );
```

**Comment by abdelaziz-mahdy** [comment]
okay thank you very much, the download completes using the mentioned branch

**Comment by crifurch** [comment]
ok, i will update package now
