### ISSUE TITLE
Timeout Error 

### ISSUE THREAD

**Issue by mhanzla80** [crifurch/pure_ftp#5]
On Connect Method

```dart
await ftpSocket
      .connect(
    config['username'],
    config['password'],
    account: config['account'],
  )
      .then((value) {
    print('Connected');
  });
```

app stuck on`await read()` and throw timeout exception

@crifurch any solution ?

**Comment by crifurch** [comment]
@mhanzla80 Hi, sorry for long time answer, i was without internet access, i uploaded new version 0.5.2 try it, check updates in example

**Comment by crifurch** [comment]
I found that all perfectly work on Linux, but don't work on Windows. I will try found solution

**Comment by crifurch** [comment]
@mhanzla80 I fixed problem
