### ISSUE TITLE
Non-ASCII code no

### ISSUE THREAD

**Issue by wuujiann** [crifurch/pure_ftp#9]
Using the following code from your example,  listNames() display non-ANSI characters in filename as '?'.  What do I need to set so that non-ASCII can be displayed properly.
```
await client.currentDirectory.listNames().then(print);
```
**Output:**
````
flutter: [/bird park_restored.jpeg, /????.jpg]

**Comment by wuujiann** [comment]
Turns out that you need to send "OPTS UTF8 ON" after socket.connect(host,port).

**Comment by crifurch** [comment]
@wuujiann try last version
